/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HoroscopoDoDiaChar123CategoriaChar125SignoRouteImport } from './routes/horoscopo-do-dia{-$categoria}/$signo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopoDoDiaChar123CategoriaChar125SignoRoute =
  HoroscopoDoDiaChar123CategoriaChar125SignoRouteImport.update({
    id: '/horoscopo-do-dia{-$categoria}/$signo',
    path: '/horoscopo-do-dia{-$categoria}/$signo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/horoscopo-do-dia{-$categoria}/$signo': typeof HoroscopoDoDiaChar123CategoriaChar125SignoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/horoscopo-do-dia{-$categoria}/$signo': typeof HoroscopoDoDiaChar123CategoriaChar125SignoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/horoscopo-do-dia{-$categoria}/$signo': typeof HoroscopoDoDiaChar123CategoriaChar125SignoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/horoscopo-do-dia{-$categoria}/$signo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/horoscopo-do-dia{-$categoria}/$signo'
  id: '__root__' | '/' | '/horoscopo-do-dia{-$categoria}/$signo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HoroscopoDoDiaChar123CategoriaChar125SignoRoute: typeof HoroscopoDoDiaChar123CategoriaChar125SignoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopo-do-dia{-$categoria}/$signo': {
      id: '/horoscopo-do-dia{-$categoria}/$signo'
      path: '/horoscopo-do-dia{-$categoria}/$signo'
      fullPath: '/horoscopo-do-dia{-$categoria}/$signo'
      preLoaderRoute: typeof HoroscopoDoDiaChar123CategoriaChar125SignoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HoroscopoDoDiaChar123CategoriaChar125SignoRoute:
    HoroscopoDoDiaChar123CategoriaChar125SignoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
